### ISSUE TITLE
Base-level rules cannot contain the parent-selector-referencing character '&'.

### ISSUE THREAD

**Issue by otherguy** [themekit/bootstrap-layout#2]
Compilation gives me an error with _gulp-sass@2.3.0_:

```
Sass Compilation Failed: node_modules/bootstrap-layout/src/sass/sidebar/_layout.scss
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.

       Backtrace:
        node_modules/bootstrap-layout/src/sass/sidebar/_layout.scss:135, in mixin `@content`
        node_modules/bootstrap/scss/mixins/_breakpoints.scss:73, in mixin `@content`
        node_modules/bootstrap/scss/mixins/_breakpoints.scss:60, in mixin `media-breakpoint-down`
        node_modules/bootstrap/scss/mixins/_breakpoints.scss:72, in mixin `@content`
        node_modules/bootstrap/scss/mixins/_breakpoints.scss:50, in mixin `media-breakpoint-up`
        node_modules/bootstrap/scss/mixins/_breakpoints.scss:71, in mixin `media-breakpoint-only`
        node_modules/bootstrap-layout/src/sass/sidebar/_layout.scss:126
        on line 135 of node_modules/bootstrap-layout/src/sass/sidebar/_layout.scss
>>      .si-#{$d}1-xs & {
   --^
```

This seems to be due to this rule in `_layout.scss`:

```
    // override .si-[l|r]1-xs
    @each $d, $direction in (l: left, r: right) {
        .si-#{$d}1-xs & {
            margin-#{$direction}: 0;
        }
    }
```

Laravel Elixir uses libsass 3.3.5.

**Comment by NourSammour** [comment]
Hi @darkwinternight,
could you solve the issue?

**Comment by otherguy** [comment]
Well yes, by forking the repo and commenting out that rule, because I don't need it. But generally, no. It seems that the issue has something to do with SASS itself.

My knowledge of SASS is limited though, so I'm unsure how to fix this.
- https://github.com/sass/sass/issues/286 
- https://github.com/sass/libsass/issues/930

**Comment by NourSammour** [comment]
@darkwinternight thanks for your quick response
For me i imported the `dist/bootstrap-layout.css` instead of `scss` file

**Comment by otherguy** [comment]
Well, that's not a real solution for me since another project depends on `bootstrap-layout`, causing errors when I run the SASS compiler via `gulp`.

**Comment by lazabogdan** [comment]
Hey guys, 

Sorry for the delay. It's because of a recent update of gulp-sass which upgraded to libsass 3.3.5. We'll release a fix in the following days but for now you can downgrade gulp-sass to 2.2.0 and it should work:

npm install gulp-sass@2.2.0

**Comment by otherguy** [comment]
Thanks @lazabogdan! I assumed as much but couldn't fix it myself. Downgrading gulp-sass didn't do it for me either, though I didn't dig any deeper.

**Comment by otherguy** [comment]
Yay, thanks @lazabogdan :) Will test tomorrow!
